// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'src/data/app_error_test.dart' as src_data_app_error_test;

void main() {
  src_data_app_error_test.main();
}
